### ISSUE TITLE
Shared passwords Safari

### ISSUE THREAD

**Issue by Mauricevb** [JadenGeller/Helium#104]
Is it possible to share Safari settings and passwords with Helium? On iOS you have something like 'SFSafariViewController' do this, but I don't know about OSX.

**Comment by slashlos** [comment]
For my forks - He3, I had looked into that, and sadly that view controller is iOS only. Hopefully once day there will be a level set of functionality - i.e., observable properties, consistent / comparable UI objects, etc.
