### ISSUE TITLE
Chrome/other browsers alternative for new Safari share link feature

### ISSUE THREAD

**Issue by SamHH** [JadenGeller/Helium#117]
As far as I'm aware the new feature to share a link with Helium in 1.9 in confined to Safari. Presumably there should be a way of doing this in Chrome and other browsers via an extension - possibly launch the specified app (using helium:// or something) with the page URL?

**Comment by JadenGeller** [comment]
Sure, somebody just needs to make that extension. It should be sure simple.

**Comment by JadenGeller** [comment]
Also, the share menu is a system-wide feature (this isn't just a Safari extension). Chrome just chooses to be non-standard and not implement it. Boo :p

**Comment by SamHH** [comment]
Aha, I see. I've been toying with making extensions and am roughly familiar with how to do that - what would be the best method? The helium:// idea I had or something else? (I'm a web developer but not so familiar with this sort of thing.)

**Comment by jeromecarney** [comment]
This good ol' fashion bookmarklet is working in Safari and Firefox on Mac:
*javascript:window.location="helium://"+location.href.replace(/https?:\/\//i,%20"")*

You could include a draggable bookmarklet on the Helium home page, that users would then just drag to their bookmarks/favorites toolbar.

**Comment by JadenGeller** [comment]
That's a decent idea. Feel free to submit a pull request, and I'll merge it if it feels clean/simple enough.

**Comment by SamHH** [comment]
I'm going to work on an extension as I said before but I'm happy for that to be my own hobby side project mostly for personal use.

That bookmarklet above works really nicely.

**Comment by SamHH** [comment]
@JadenGeller I've created said extension (very basic to begin with, just a context menu link) and am planning to name it Share for Helium. At the moment it's also using the Helium logo but I expect you'll prefer me to change that before I upload to the Chrome web store, and if so no problem at all.

Let me know.

**Comment by JadenGeller** [comment]
Feel free to use the Helium logo for now as long as you're clear in the description that it's an unofficial extension. :smile:

**Comment by SamHH** [comment]
Awesome, will do. Thanks!

**Comment by SamHH** [comment]
I've made a Chrome extension for this! https://chrome.google.com/webstore/detail/eohchkmfadpiidgfhobbibfgfpakbikd
