### ISSUE TITLE
OS X Compatibility

### ISSUE THREAD

**Issue by Jake-Evans** [JadenGeller/Helium#122]
Any chance of a port down to OS X 10.9.5?

**Comment by 1-61803** [comment]
Say 10.8, or even 10.6 — that shouldn't be such a problem :)

**Comment by Jake-Evans** [comment]
Where would I be able to get the release compatible with that version?

**Comment by 1-61803** [comment]
I don't know what you mean — I'm just saying that backwards compatibility shouldn't be such a problem for the dev to achieve.

**Comment by JadenGeller** [comment]
The app uses `WKWebView`, introduced in OS X 10.10. The app can be made compatible with earlier versions of OS X by using `WebView` instead, introduced in OS X 10.2. If you revert enough commits, in fact, I think there's a version of the app built with that class. I am not interested in using it moving forward, however. I don't have the time to support legacy OSes, but if you'd like to make a fork that uses `WebView`, @1-61803, definitely feel free too. Lot's of users would love it!
