### ISSUE TITLE
Youtube links with time attribute doesn't work as expected

### ISSUE THREAD

**Issue by entriol** [JadenGeller/Helium#125]
When I go to https://youtu.be/d0yGdNEWdn0?t=60 in Helium, video doesn't start from defined seek time. I think [the code in here](https://github.com/JadenGeller/Helium/blob/a2d0e4d320fd8a01be7af4aadedfa0c63eab3928/Helium/Helium/WebViewController.swift#L143) needs some improvement. (I have no experience in swift, that's why I didn't send a PR)

**Comment by nmcdonaldd** [comment]
Working on that. I'll submit PR when I get it worked out.
