### ISSUE TITLE
Plug-in blocked

### ISSUE THREAD

**Issue by raidiant** [JadenGeller/Helium#13]
Plugin needed for viewing Youtube and Twitch is blocked on my instance of Helium.
![schermafdruk 2015-04-13 13 18 42](https://cloud.githubusercontent.com/assets/5798467/7114640/a513b18e-e1df-11e4-95ac-31e42711151e.png)

**Comment by JadenGeller** [comment]
Is your flash player up to date?

**Comment by raidiant** [comment]
It was not, It works now, thanks so much!
Nice work as well!
