### ISSUE TITLE
Add option for zero transparency

### ISSUE THREAD

**Issue by mrtnbroder** [JadenGeller/Helium#15]
It would be nice to see the whole window by 100% (so that there is 0% transparency).

**Comment by dhruska** [comment]
I think this is a fair use case. You can basically do that now by turning Translucent off, but then the window is always clickable.

**Comment by JadenGeller** [comment]
Can you elaborate on what the use case of this is? I can't imagine ever wanting to click on content behind the window when the window is completely opaque.

**Comment by dhruska** [comment]
I guess the main reason I thought it would be useful would be so that you can have the video be full opaque and not accidentally click on it or move it as you're working.

**Comment by JadenGeller** [comment]
That makes sense, cool.

**Comment by mrtnbroder** [comment]
yeah sorry, maybe didn't explain it clear enough. Exactly what @dhruska said!

**Comment by codenamezjames** [comment]
It would be cool for mouse over. Especially if it were to allow you to click under the window.
