### ISSUE TITLE
App has name conflict with existing app

### ISSUE THREAD

**Issue by BrianGilbert** [JadenGeller/Helium#157]
http://www.clockworkmod.com/carbon

![downloads 2016-04-19 08-50-48](https://cloud.githubusercontent.com/assets/114017/14622230/d26774f8-060b-11e6-8ef7-8fb9dbbe928e.png)

**Comment by JadenGeller** [comment]
I'm not interested in changing the name, so you'll have to probably keep the apps in separate directories unfortunately. Sorry about that.
