### ISSUE TITLE
Any way to debug pages not working?

### ISSUE THREAD

**Issue by jimbofreedman** [JadenGeller/Helium#208]
Hi, 

I'm using Helium for a task management web page I wrote myself. My async calls don't seem to work in Helium - perhaps something to do with cookies/auth. Everything works fine in Chrome and Firefox so I'm wondering if there's any way to find out what it's trying to send?

Jimbo

**Comment by stek29** [comment]
@jimbofreedman Hellium uses WebViews, which are Safari based

**Comment by jimbofreedman** [comment]
Thanks! Will test my page in Safari then and see if I can replicate.
