### ISSUE TITLE
Youtube live and Twitch streams NOT working anymore

### ISSUE THREAD

**Issue by danielcarletti** [JadenGeller/Helium#213]
Hello, I've been having issues with youtube live streaming and Twitch. They don't load at all.

On Twitch, the video doesn't load at all.
On youtube live videos, it loads a couple of frames and then it enters the loading screen, where it stays forever.

Examples: 
Twitch: https://www.twitch.tv/beyondthesummit
Youtube: https://www.youtube.com/watch?v=DG169aR-72Y

**Comment by stek29** [comment]
What are app and system versions?

**Comment by danielcarletti** [comment]
Version 2.0 (20)
MacOS Sierra 10.12.4 (16E195)

**Comment by stek29** [comment]
Latest from mac app store for me opened twitch page
![image](https://cloud.githubusercontent.com/assets/11808223/25813445/3cf2a28a-3422-11e7-98de-3b3721ba04a2.png)

Compiled from #216 works perfectly fine
![image](https://cloud.githubusercontent.com/assets/11808223/25813563/c0096726-3422-11e7-9121-5357253e8ef2.png)

But YouTube live streams seem to be broken indeed.

**Comment by stek29** [comment]
I can't reproduce it anymore. Maybe youtube has changed something. 
@danielcarletti, do they work for you?

**Comment by danielcarletti** [comment]
Youtube worked after a reload! 
Example used: https://www.youtube.com/watch?v=qIDxRqd5J6o
Thanks, I'm closing the issue now.
