### ISSUE TITLE
Not running on OS X 10.8.5

### ISSUE THREAD

**Issue by rreddy66** [JadenGeller/Helium#23]
When I download and run the app I get an error saying the application requires OS X 10.10 or later. Is there a work around for this that would allow me to not update my operating system, but use the app?

Thanks.

**Comment by bradparks** [comment]
i concur! I'm on 10.8.5 as well due to a corporate lock down of mac versions, at a big company.... much appreciated if this could work on 10.8.5!

**Comment by JulesOpp** [comment]
Functionality with 10.7.4 would be incredible

**Comment by jaflo** [comment]
+1 Is there any API that requires 10.10? Otherwise other versions should be possible.

**Comment by JadenGeller** [comment]
I'm planning to add support for older versions of OS X in the next update. Stay tuned!
