### ISSUE TITLE
REQ: Watch Later

### ISSUE THREAD

**Issue by proactivematter** [JadenGeller/Helium#245]
Hello,

I would find it very useful to be able to send links to Helium to watch later. Nothing fancy, just a list with the channel name + video titles would be OK.

Thanks!

**Comment by slashlos** [comment]
See my fork of [Helium 3](https://github.com/slashlos/Helium).  It maintains a playlist catalog of play items.

**Comment by JadenGeller** [comment]
This is a neat idea, but it's out-of-scope for what I plan to implement with Helium—sorry!

Perhaps there's a watch-it-later website you could use with Helium?
