### ISSUE TITLE
alternative to helium

### ISSUE THREAD

**Issue by pvinis** [JadenGeller/Helium#260]
try this one.
https://github.com/kamranahmedse/pennywise

**Comment by curiouscrusher** [comment]
As much as I've enjoyed Helium over the years, it seems development has slowed down. Also it doesn't seem to work with Plex (macOS App Store Version), which brought me here. Seems like Pennywise is a decent replacement with active development, and it even works with Plex 💯

**Comment by slashlos** [comment]
Yes stale, here, but I’ve forked off and posted video [v3](https://github.com/slashlos/Helium/releases/tag/4121) where I’m active. You might take a look

**Comment by curiouscrusher** [comment]
Oh nice, thanks for the heads up @slashlos, I'll be sure to check it out!

**Comment by pvinis** [comment]
I remember trying your fork but could

**Comment by slashlos** [comment]
Fine; if you do fine an issue, please log along with background info - version, kit or self built, and reproducer, thanks.
