### ISSUE TITLE
Few bugs

### ISSUE THREAD

**Issue by JustSage** [JadenGeller/Helium#261]
Hi, this is my first time posting on Github so bare with me if there are any formatting issues :|.

The app crashed several times while attempting to adjust the transparency, no errors were given it just crashed.
Another issue I have is that it won't become the menu bar when clicking on it and I have to restart the application for it to become the menu bar ( and play around with the features it has to offer ) ...

Hope there are some answers for it. Cheers :)

**Comment by slashlos** [comment]
Try an active fork such as (mine) [Helium 3](https://github.com/slashlos/Helium/releases/tag/4125)

**Comment by RabbitJazz** [comment]
Thank you so much :) !
Works flawlessly now.

**Comment by JadenGeller** [comment]
I rearchitected the menu bar code (though its still a WIP), so this issue is probably fixed (or at least outdated)
