### ISSUE TITLE
Inspector

### ISSUE THREAD

**Issue by brandonmcconnell** [JadenGeller/Helium#263]
Some videos I play using Helium have forced outer margins set in the pages' CSS styles. Any way of implementing an inspector, even the standard Safari for me to make simple adjustments to pages I land on before watching videos?

**Comment by slashlos** [comment]
You might try [Helium](https://github.com/slashlos/Helium/releases/tag/4125) 3 my fork of this project; in review at the app store.

Available soon - build 4126 plus, is exposure of Developer Inspection windows:

![Screen Shot 2019-06-05 at 7 46 29 AM](https://user-images.githubusercontent.com/3155005/58954117-437a1900-8766-11e9-96f0-7ca8c13768c5.png)
![Screen Shot 2019-06-05 at 7 47 05 AM](https://user-images.githubusercontent.com/3155005/58954118-437a1900-8766-11e9-9564-c0cb3abf8254.png)
![Screen Shot 2019-06-05 at 7 47 29 AM](https://user-images.githubusercontent.com/3155005/58954119-437a1900-8766-11e9-9b1a-a37427c47c8d.png)

**Comment by JadenGeller** [comment]
c465d11de576ddc6f0c4f4e9268e38d6f2c84d4a adds `Show Inspector` to the right click menu
