### ISSUE TITLE
Youtube fullscreen not working

### ISSUE THREAD

**Issue by saiajay5674** [JadenGeller/Helium#264]
Fullscreen does not work on youtube.com 
When I try using fullscreen it says browser does not support fullscreen

**Comment by slashlos** [comment]
This project is stale; try a fork like mine - [Helium](https://github.com/slashlos/Helium/releases/tag/4125)

**Comment by JadenGeller** [comment]
WKWebView doesn't support fullscreen. This is an Apple limitation.
