### ISSUE TITLE
UX improvements

### ISSUE THREAD

**Issue by Pompiedom** [JadenGeller/Helium#269]
Love the app, two 'small' suggestions to improve the UX.

1. Start Helium with the locationbar open (and focus on it).
2. When the locationbar is openend move the focus directly on it so you can directly type.

Thats it! <3

**Comment by JadenGeller** [comment]
I now focus the location bar on show window in d363cfd44d975019392c67410c96d3894be1ff56

**Comment by JadenGeller** [comment]
<img width="592" alt="Screen Shot 2020-05-24 at 7 49 32 PM" src="https://user-images.githubusercontent.com/4544152/82773844-ef919580-9df7-11ea-993a-865224788991.png">
