### ISSUE TITLE
Window UX improvement

### ISSUE THREAD

**Issue by kabyanil** [JadenGeller/Helium#270]
hey, thanks for making such a useful app. before getting helium, I was using safari's picture in picture mode. I switched to helium because it adds playback controllable functionality within the window, whereas the safari mode only adds the pause button. however, I really liked the look of safari's window. if you could replicate that same look, meaning to remove the window bar(which shows the title of the video), it would look a lot cleaner and save some space too.

**Comment by slashlos** [comment]
This port is pretty stale; you might try a fork such which feature a minimalist view; see [Helium  3 releases](https://github.com/slashlos/Helium/releases), I maintain.

**Comment by JadenGeller** [comment]
Helium already allows you to hide the window bar!
