### ISSUE TITLE
When setting the location from URL focus the cursor on the UITextView

### ISSUE THREAD

**Issue by Matthewspear** [JadenGeller/Helium#271]
When setting location, focus the cursor to location UITextView for input.

It is frustrating to me to have to click with the cursor each time I want to paste a URL and seems to be an expected behaviour on macOS platform.

**Comment by slashlos** [comment]
This issue has been addressed in my fork of this work. Check out its [releases](https://github.com/slashlos/Helium/releases) page.

**Comment by JadenGeller** [comment]
Fixed!

**Comment by Matthewspear** [comment]
Thanks Jaden, I build and tested it – works a charm and make such a difference!!
