### ISSUE TITLE
Access local videos

### ISSUE THREAD

**Issue by elalemanyo** [JadenGeller/Helium#31]
Hi,

Will be great if you can also play local videos... something like file:///....

Thanks!
Great job!!

**Comment by JadenGeller** [comment]
You can!! Just drag and drop the file in!! (You can also put ~/the/directory/of/the/file.mp4 in, who who wants to do that) I really ought to document this.

**Comment by JadenGeller** [comment]
I think I'll add explicit support for this in the menubar though. :)

**Comment by JadenGeller** [comment]
Added support in the menubar! Woot!

**Comment by elalemanyo** [comment]
where is the support in the menubar? i did't see it...
Maybe a select item function will be also great.

Thanks!

**Comment by JadenGeller** [comment]
It's not on the website yet, but it's in the newest commit. You'll have to download and compile the project on your own, or just wait a few days.

What do you mean by a select item function?

**Comment by elalemanyo** [comment]
I thought something like with the shortcut U+2318+U+21E7+a, then will open a finder window, something like on mail App to add an Item to a Mail (http://screencast.com/t/4IG21fQj).

**Comment by JadenGeller** [comment]
That's exactly what I added.

**Comment by elalemanyo** [comment]
Upps! Sorry, I didn't compile... I will do that.

Thanks for your fast answer and for the app!
Great work!

**Comment by elalemanyo** [comment]
compiled and getestet.... Perfect!

**Comment by JadenGeller** [comment]
Awesome!
