### ISSUE TITLE
Add Opacity shortcuts

### ISSUE THREAD

**Issue by elalemanyo** [JadenGeller/Helium#36]
Hi,

Will be great if you add shortcuts to control the opacity, maybe using the numbers.

Thanks!

**Comment by LeonardoCardoso** [comment]
Feature added on pull request https://github.com/JadenGeller/Helium/pull/40

**Comment by kylepierce** [comment]
You can just add a shortcut in keyboard preferences.

**Comment by JadenGeller** [comment]
Closed by #40

**Comment by elalemanyo** [comment]
Already testet... Works perfectly! 
Thanks
