### ISSUE TITLE
Netflix System Requirements Error

### ISSUE THREAD

**Issue by maclover7** [JadenGeller/Helium#4]
When trying to watch Netflix (running Yosemite), I encountered a Netflix error. Check out the screenshot below. Not sure what's going on here...

http://cl.ly/image/3e3Q1I3L392g

**Comment by brks** [comment]
I get exactly the same error. :(

**Comment by JadenGeller** [comment]
Fixed! Unfortunately Silverlight is now required for Netflix playback, but I think that's a reasonable solution.
