### ISSUE TITLE
Code issues

### ISSUE THREAD

**Issue by nathggns** [JadenGeller/Helium#41]
HeliumPanelController:

- Should probably define your properties at the top of the class.
- Is NSNotificationCenter.defaultCenter() instant? If not you should cache it

**Comment by JadenGeller** [comment]
I agree that code might need to be refactored, but this isn't worthy of an issue IMO.

NSNotificaitonCenter.defaultCenter() is a singleton, so the current usage is fine. I plan to move away from notification center though, I'm abusing it.
