### ISSUE TITLE
AVI / MKV files playback issue

### ISSUE THREAD

**Issue by ashfame** [JadenGeller/Helium#45]
The player loads up and the time starts in playback but no audio or video.

**Comment by ialexryan** [comment]
This is actually an issue with Safari, not Helium. The same behavior will occur if you try to open either an AVI or MKV file in Safari.

The only real possible solutions to this are integrating a media player that supports those file formats and codecs, which is outside the scope of this project at this point. Bug Apple to support them natively!

**Comment by JadenGeller** [comment]
You *may* be able to use the VLC web plugin to get this to work, but I'm not sure I'd recommend it. It doesn't look like they have any stable releases, so you'd be stuck with a nightly build. Could be worth a try though ¯\_(ツ)_/¯ http://nightlies.videolan.org/build/macosx-intel/?C=M;O=D

**Comment by ashfame** [comment]
Gotcha! Thanks

**Comment by drreen** [comment]
Hey guys

can you provide brief steps to play MKV with VLC web plugin + helium?
In case anyone was actually able to achieve that. :)

**Comment by ashfame** [comment]
@drreen VLC can actually stay on top of all other windows. It has an option in preferences.

**Comment by drreen** [comment]
@ashfame I have tried that, but VLC stays in focus.
I want to continue working on my stuff while viewing the MKV content.
I haven't found a way to replicate the exact same behaviour as Helium in VLC.

**Comment by ashfame** [comment]
@dreen It doesn't for me. I can continue to work exactly like Helium except the transparency bit.

**Comment by drreen** [comment]
@ashfame Can you tell me the exact settings to achieve that?

**Comment by ashfame** [comment]
@drreen Under `Video` menu, select `Float on top`

**Comment by drreen** [comment]
Then the "click-through" part in VLC is still missing like in Helium :)

**Comment by elijahmurray** [comment]
A work around is to use plex.tv. It creates a free media server. It handles the rendering and provides a web interface for watching all your .mkv files through Helium! @drreen  @ashfame  @JadenGeller

**Comment by jamescoletti** [comment]
With the latest version of Plex + latest version of Helium from Mac App Store, videos won't play for me. I'm logging into the Plex interface through Helium and then selecting a video to play, but then it just shows the player with video artwork and loader and the video never plays. Anyone else experiencing this issue?

**Comment by Metroxe** [comment]
@jamescoletti I'm also experiencing this issue. I tried using dropbox to stream my video after this to find a really weird occurrence. I put an mkv on dropbox, then view it inside helium. It will act the same as plex does, where you simply just see the current buffered frame or starting thumbnail. But if I open the same link in chrome and start buffering the video and playing it, then helium will begin to play. Really not sure what is causing this however.

**Comment by jamescoletti** [comment]
@Metroxe FYI I ended up compiling a build of Helium from source, seemingly much newer than what's in the Mac App Store and it's working fine.
