### ISSUE TITLE
Fade out on hover

### ISSUE THREAD

**Issue by JadenGeller** [JadenGeller/Helium#5]

**Comment by JadenGeller** [comment]
Add option so that, when mouse moves over a translucent window, it fades out even more (maybe completely) as to allow usage of computer still

**Comment by JadenGeller** [comment]
Another possibility, thew window moves out of the way avoiding the mouse. It'd be an interesting PIP concept that wouldn't require translucency.

**Comment by JadenGeller** [comment]
Another idea: potentially make window less translucent when active? The only issue with this is we don't want to confuse the user about the current translucency setting.

**Comment by maxnowack** [comment]
+1

**Comment by JadenGeller** [comment]
Done! https://github.com/JadenGeller/Helium/releases/tag/v1.8
