### ISSUE TITLE
Support for HTML5 Premium Video (Netflix & YouTube without plugins)

### ISSUE THREAD

**Issue by alexkadis** [JadenGeller/Helium#54]
First, just wanted to say this app is fantastic! Thank you for creating it.

I was researching to see why Safari is able to go HTML5 video with Encrypted Media Extensions (EME), but Helium isn't — relegating us to installing Silverlight and Flash for Netflix and YouTube respectively.

It seems like there may be a way to make a UIWebView able to use EME. I found two resources, [this Apple technote](https://developer.apple.com/library/ios/technotes/tn2232/_index.html#//apple_ref/doc/uid/DTS40012884-CH1-SECUIWEBVIEW), and [this blog article with example code](http://www.html5rocks.com/en/tutorials/eme/basics/).

The passage that makes me think this might be possible:
> UIWebView does not provide any way for an app to customize its HTTPS server trust evaluations (r. 10131336) . You can work around this limitation using an NSURLProtocol subclass, as illustrated by [Sample Code 'CustomHTTPProtocol'](https://developer.apple.com/samplecode/CustomHTTPProtocol/index.html).

Thanks!

**Comment by JadenGeller** [comment]
Nice!! That seems like it'll be super useful! I'm catching up on schoolwork right now, but once finished, this'll be on the top of my priority list. Thanks!

**Comment by lologhi** [comment]
Good news !

**Comment by emilstahl** [comment]
+1 @lologhi

**Comment by vincentorback** [comment]
Sweet! :+1:
