### ISSUE TITLE
Possibility to change dns settings

### ISSUE THREAD

**Issue by basdewit** [JadenGeller/Helium#58]
Maybe It would be possible to add a setting to change the DNS settings so country limited content could be viewed.

**Comment by ialexryan** [comment]
DNS settings should generally not be modified on a per-application basis. If you want to do this, change your DNS settings in System Preferences -> Network.

You may also have better success accessing country-limited content by subscribing to a VPN located in that country and then sending all your system traffic over that VPN connection.
