### ISSUE TITLE
Loading icon/indicator while Helium loads new URL

### ISSUE THREAD

**Issue by bl4de** [JadenGeller/Helium#60]
Hi,

First of all - thank you for Helium, it's really useful while coding and watching tutorial or conference in the same time.

It would be nice to implement some loading indicator while Helium loads new URL. Right now, after CMD+L and enter url, nothing happens and it looks like Helium doesn't work anymore :)

It's not a big issue of course, some nice-to-have rather than "killer feature" ;)

**Comment by JadenGeller** [comment]
This feature was added by #49. In the future, we might change the visual representation of it, but for now it's something.

**Comment by bl4de** [comment]
Thanks, I didn't notice this one.
