### ISSUE TITLE
Flash Plugin Blocked

### ISSUE THREAD

**Issue by dhalima3** [JadenGeller/Helium#67]
Hi, awesome job on the app!  I am trying to watch a live sports event through the Watch ESPN web application, but whenever I access the url through Helium, I am presented with a 'Blocked Plugin' screen.  I have ensured that my flash plugin is up to date, but the problem still persists.

**Comment by andrewparrish** [comment]
Same issue observed on HBO go.
![screen shot 2015-05-04 at 1 02 44 pm](https://cloud.githubusercontent.com/assets/3136770/7457895/dca64d1c-f25d-11e4-8773-e9697488e27c.png)

**Comment by JadenGeller** [comment]
You're sure that you have flash player installed in **Safari***, not just Chrome, right?

**Comment by andrefarzat** [comment]
In my case, just updating the Flash Player in Safari solved the issue
