### ISSUE TITLE
Fullscreen not working on Vice.com

### ISSUE THREAD

**Issue by alexander** [JadenGeller/Helium#7]
It seems that this app is not always honoring the fullscreen feature on some players. Here's one case: http://www.vice.com/en_se/video/vice-meets-nick-cave.

**Comment by JadenGeller** [comment]
Full screen seems to be mostly working for me. The only issue is the OS X menu bar still appears. Is that what you're experiencing?

**Comment by dhruska** [comment]
Seems to not be working for HBO Now. Or rather, it fullscreens the entire computer window. Is that what should be happening?

**Comment by JadenGeller** [comment]
Yes, it is not possible to take over fullscreen and make it only apply to the window.
