### ISSUE TITLE
Playback Speed

### ISSUE THREAD

**Issue by horak** [JadenGeller/Helium#72]
Would be really nice to be able to control playback speed on local videos. If anyone has an ideas on how to approach this, please tell, I'm willing to give it a try!

**Comment by JadenGeller** [comment]
I can't think of any feasible solution. Opening a video in Helium is equivalent to opening it in Safari, so really you'd need some browser extension (that supports that feature) that takes over local video playback. I know VLC has a Safari extension, but I haven't tested it with Helium and last I heard, their extension wasn't working properly in the most recent versions of OS X.

**Comment by horak** [comment]
Yeah bummer :/ 
I might just create a script that converts video playback speed locally then. Should this be closed do you think? It is a pipe dream?

**Comment by JadenGeller** [comment]
Yeah, I think that's the best solution, unfortunately.

**Comment by yesiamben** [comment]
@horak, @JadenGeller -
Forgive replying to an old topic (especially if you have a better solution to this already), but have just found helium (thanks, it's ace!) and this was exactly my problem and I couldn't find a decent answer. Want to watch local videos but faster. Best solution I came up with is below (forgive the unnecessary mess of code - it's taken from this gist: https://gist.github.com/mengguoru/1c04b21ca048a670d84a - with some _very_ quick styles added). Right now you have to edit the file to play videos, but it would only take ten minutes to make add a video path via a query string or something.

~~~~
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>Html5 Video Player</title>
	<link href="http://vjs.zencdn.net/5.0.2/video-js.css" rel="stylesheet">
    <script src="http://vjs.zencdn.net/5.0.2/video.js"></script>
    <style type="text/css">
	body, div, dl, dt, dd, ul, ol, li, h1, h2, h3, h4, h5, h6, pre, 
	form, fieldset, input, p, blockquote, table, th, td, embed, 
	object, menu, nav, aside, section, article {
		padding: 0;
		margin: 0;
	}

	body {
		font-size: 62.5%;
		font-family: Arial, Helvetica, sans-serif;
		/*height: 100vh;*/
		min-height: 100vh;
		color: #fff;
		background-color: #000;
	}
	
	::selection {
	}
	::-moz-selection {
	}
	
	a {
		color: #00f;
	}
		a:hover {
		}
	.videofull {
		height: 100vh;
		float: left;
		width: 100%;
	}
		.videofull > div {
			height: 100%;
			width: 100%;
		}
    </style>
</head>
<body>
	<div class="videofull">
	<video class="video-js vjs-default-skin" controls preload="auto" data-setup='{ "playbackRates":[0.25,0.5,1,1.25,1.5,2]}'>
  <!-- let src point to your video's File URL on your computer-->
        <source src="yourvideo.mp4" type='video/mp4' /> 
        {# <source src="xxx.webm" type='video/webm' />
        <source src="xxx.ogv" type='video/ogg' /> #}
  </video>
  </div>
 </body>
</html>
~~~~
