### ISSUE TITLE
Can't watch videos if there's an ad

### ISSUE THREAD

**Issue by fabersky** [JadenGeller/Helium#74]
Want to watch a video, but if there's an ad in the middle of the page (the typical ad that opens a new page when you click on "X" to close it), when clicking on it Helium goes to another page and is not possible to come back to video.
I'd suggest to add this feature: allow multiple tabs.

**Comment by JadenGeller** [comment]
Multiple windows are planned for a future release—that should fix this.

**Comment by fabersky** [comment]
Great!
