### ISSUE TITLE
Display Helium in full screen apps

### ISSUE THREAD

**Issue by WolfieZero** [JadenGeller/Helium#76]
Be awesome if when you set an app to fullscreen you can still have Helium floating; making it almost sticky to the screen rather than a space.

**Comment by JadenGeller** [comment]
That admittedly would be cool, but I don't believe it is possible to have an app overlap a fullscreen app in OS X. If you find info that says otherwise, feel free to let me know.

**Comment by net** [comment]
+1

Maybe resist this @JadenGeller? I almost exclusively run apps in fullscreen mode and I know I'm not the only one.

**Comment by JadenGeller** [comment]
It looks like someone added the feature already! https://github.com/JadenGeller/Helium/pull/100

**Comment by SamHH** [comment]
Ah that's fantastic! I'm on Version 1.6 (12) - when abouts can I expect that to make its way live?

**Comment by net** [comment]
@SamHH I actually went ahead and built it myself. If you're trusting I could send you it.
