### ISSUE TITLE
Faulty Youtube playback

### ISSUE THREAD

**Issue by sameerismail** [JadenGeller/Helium#79]
I'm having issues with playback from any Youtube video, in Chrome it works perfectly but in Helium it goes into the buffering state every couple of minutes and I have to manually rewind and replay for it to load properly.

**Comment by vincentorback** [comment]
+1

Same as [#34](https://github.com/JadenGeller/Helium/issues/34)

**Comment by garzito** [comment]
Having the same issue here!

**Comment by ivobenedito** [comment]
+1

**Comment by laukus** [comment]
+1 too

**Comment by squallstar** [comment]
+1

**Comment by fosron** [comment]
+1

It works on 144p, nothing more up works.
