### ISSUE TITLE
Request: Stay on top even with spaces switch

### ISSUE THREAD

**Issue by fosron** [JadenGeller/Helium#83]
I'm using spaces constantly and i think it would be great if helium would not move with spaces.

**Comment by maxnowack** [comment]
+1

**Comment by maxnowack** [comment]
+1

**Comment by JadenGeller** [comment]
I plan to add this as a setting in the future. It's super simple, but I can imagine not everyone wanting this.

**Comment by htkm** [comment]
+1

**Comment by chedched** [comment]
+1. Fantastic work btw.

**Comment by zinkkrysty** [comment]
This would be great to have, as I use spaces a lot to organize my work. Currently I use Opera with the pop-out video feature, which works as this app, and I probably will only use it for web videos. However the reason I wanted to install Helium is to have the "stay on top on all spaces" option. Any news on the development of this feature?

**Comment by JadenGeller** [comment]
I think this was closed by https://github.com/JadenGeller/Helium/pull/100.
