### ISSUE TITLE
Create a browser plugin to load current page/video in Helium

### ISSUE THREAD

**Issue by bhagyas** [JadenGeller/Helium#86]
What's above.

Also an action for new links "Send to Helium".

**Comment by brunowego** [comment]
+

**Comment by distantnative** [comment]
+1 for share extension

**Comment by hffmnn** [comment]
Should be done with latest release https://github.com/JadenGeller/Helium/releases/tag/1.9

**Comment by Wookbert** [comment]
+1
The extension should allow you to select just the video to be played in an iframe, so any surrounding info and ads are removed.

**Comment by JadenGeller** [comment]
@hffmnn I correct, this is implemented now. I'll close this request.

**Comment by JadenGeller** [comment]
@Wookbert Feel free to open a separate issue regarding this. I'm not exactly sure how to accomplish it though, and don't have the time to play around with it right now.
