### ISSUE TITLE
URL Scheme for integration with other apps?

### ISSUE THREAD

**Issue by chrismetcalf** [JadenGeller/Helium#88]
It'd be awesome if Helium had a URL scheme so we could have like a bookmarklet or Chrome Extension to open a URL in Helium.

**Comment by harunurhan** [comment]
I checked the code and it has URL scheme. You can use from terminal by entering 

`$open helium://https://www.youtube.com/your_video`

About Chrome Extension, Google Chrome does not allow directly run a command (like above). It only allows you to communicate with a particular app by message passing and this requires some changes on  App code.

https://developer.chrome.com/extensions/nativeMessaging

**Comment by ryh** [comment]
done that #33

**Comment by runofthemill** [comment]
fyi - I just made an alfred workflow for Helium, which you can grab [here](https://github.com/runofthemill/heliumlauncher-alfred). Lets you open a URL in Helium with `h:{query}` :)

**Comment by mizterp** [comment]
Couldn't get it to work via iTerm. But I got it to work with this AppleScript:

```
tell application "System Events"
	tell current location of network preferences
		set VPN to service "My VPN Connection" -- your VPN name here
		if exists VPN then connect VPN
		repeat while (current configuration of VPN is not connected)
			delay 1
		end repeat
	end tell	
end tell

set appname to "Helium"
tell application appname to launch
tell application "System Events"
	repeat until visible of process appname is true
		delay 0.5
	end repeat
end tell

do shell script "open helium://http://google.com" -- your default URL here
```

**Comment by txaidw** [comment]
I made this new Workflow for opening the current Safari tab video on Helium! Its available here: https://github.com/txaidw/OpenInHelium_AlfredWorkflow

I hope you enjoy!

:D

**Comment by JadenGeller** [comment]
@txaidw Really cool, nice!

**Comment by JadenGeller** [comment]
Closing because this was implemented a while ago
